version: '3.4'

services:
  storagefront:
    image: storagefront
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
    - "8090:80"
  storageback:
    image: storageback
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "7090:80"
      - "7091:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=7091
      - ASPNETCORE_Kestrel__Certificates__Default__Password=certpass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
        - ./back/cert.pfx:/https/cert.pfx:ro